// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-movements.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function textResult(value, isError = false) {
  return {
    content: [
      {
        type: "text",
        text: typeof value === "string" ? value : JSON.stringify(value)
      }
    ],
    ...isError ? { isError: true } : {}
  };
}
function requireAuth(ctx) {
  return ctx.isAuthenticated() ? null : textResult("Not authenticated", true);
}

// src/lib/mcp/tools/list-movements.ts
var list_movements_default = defineTool({
  name: "list_movements",
  title: "Listar movimientos",
  description: "Lista los movimientos financieros del usuario (ingresos, gastos, ahorros, transferencias, rendimientos) con filtros opcionales de tipo y rango de fechas.",
  inputSchema: {
    type: z.enum(["income", "expense", "savings", "transfer", "yield"]).optional().describe("Filtrar por tipo de movimiento."),
    start_date: z.string().optional().describe("Fecha inicial YYYY-MM-DD."),
    end_date: z.string().optional().describe("Fecha final YYYY-MM-DD."),
    limit: z.number().int().optional().describe("M\xE1ximo de filas (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type, start_date, end_date, limit }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let query = supabaseForUser(ctx).from("movements").select("id,date,type,detail,amount,personal_amount,currency,is_withdrawal,category:categories(name)").order("date", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (type) query = query.eq("type", type);
    if (start_date) query = query.gte("date", start_date);
    if (end_date) query = query.lte("date", end_date);
    const { data, error } = await query;
    if (error) return textResult(error.message, true);
    return { ...textResult(data), structuredContent: { movements: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-movement.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_movement_default = defineTool2({
  name: "create_movement",
  title: "Crear movimiento",
  description: "Crea un movimiento financiero (ingreso, gasto, ahorro, transferencia o rendimiento) para el usuario autenticado.",
  inputSchema: {
    date: z2.string().describe("Fecha del movimiento YYYY-MM-DD."),
    type: z2.enum(["income", "expense", "savings", "transfer", "yield"]).describe("Tipo de movimiento."),
    amount: z2.number().positive().describe("Monto en la moneda indicada."),
    detail: z2.string().optional().describe("Descripci\xF3n del movimiento."),
    category_id: z2.string().uuid().optional().describe("ID de categor\xEDa existente."),
    currency: z2.enum(["ARS", "USD"]).optional().describe("Moneda (default ARS)."),
    is_withdrawal: z2.boolean().optional().describe("Para ahorros: marca un retiro en lugar de un dep\xF3sito.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("movements").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      type: input.type,
      amount: input.amount,
      detail: input.detail ?? null,
      category_id: input.category_id ?? null,
      currency: input.currency ?? "ARS",
      is_withdrawal: input.is_withdrawal ?? false
    }).select().single();
    if (error) return textResult(error.message, true);
    return { ...textResult(data), structuredContent: { movement: data } };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool3({
  name: "list_categories",
  title: "Listar categor\xEDas",
  description: "Lista las categor\xEDas del usuario, con sus IDs, para poder asignarlas al crear movimientos o pendientes.",
  inputSchema: {
    type: z3.enum(["income", "expense", "savings", "transfer", "yield"]).optional().describe("Filtrar por tipo de categor\xEDa.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ type }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    let query = supabaseForUser(ctx).from("categories").select("id,name,type").order("name");
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return textResult(error.message, true);
    return { ...textResult(data), structuredContent: { categories: data ?? [] } };
  }
});

// src/lib/mcp/tools/list-pending.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_pending_default = defineTool4({
  name: "list_pending",
  title: "Listar pendientes",
  description: "Lista los pagos pendientes (a pagar) y/o los ingresos pendientes (a cobrar) del usuario, con sus fechas de vencimiento.",
  inputSchema: {
    kind: z4.enum(["payments", "income", "both"]).optional().describe("Qu\xE9 listar: pagos, ingresos o ambos (default both)."),
    include_settled: z4.boolean().optional().describe("Incluir los ya pagados/cobrados (default false).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, include_settled }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const supabase = supabaseForUser(ctx);
    const which = kind ?? "both";
    const result = {};
    if (which === "payments" || which === "both") {
      let q = supabase.from("pending_payments").select("id,description,amount,due_date,is_paid,category_id").order("due_date");
      if (!include_settled) q = q.eq("is_paid", false);
      const { data, error } = await q;
      if (error) return textResult(error.message, true);
      result.pending_payments = data ?? [];
    }
    if (which === "income" || which === "both") {
      let q = supabase.from("pending_income").select("id,description,amount,due_date,is_collected,category_id").order("due_date");
      if (!include_settled) q = q.eq("is_collected", false);
      const { data, error } = await q;
      if (error) return textResult(error.message, true);
      result.pending_income = data ?? [];
    }
    return { ...textResult(result), structuredContent: result };
  }
});

// src/lib/mcp/tools/create-pending-payment.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_pending_payment_default = defineTool5({
  name: "create_pending_payment",
  title: "Crear pago pendiente",
  description: "Crea un pago pendiente con fecha de vencimiento. No afecta el balance hasta marcarse como pagado en la app.",
  inputSchema: {
    description: z5.string().min(1).describe("Descripci\xF3n del pago."),
    amount: z5.number().positive().describe("Monto del pago."),
    due_date: z5.string().describe("Fecha de vencimiento YYYY-MM-DD."),
    category_id: z5.string().uuid().optional().describe("ID de categor\xEDa de gasto.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ description, amount, due_date, category_id }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("pending_payments").insert({
      user_id: ctx.getUserId(),
      description,
      amount,
      due_date,
      category_id: category_id ?? null,
      is_paid: false
    }).select().single();
    if (error) return textResult(error.message, true);
    return { ...textResult(data), structuredContent: { pending_payment: data } };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z6 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool6({
  name: "financial_summary",
  title: "Resumen financiero",
  description: "Devuelve el resumen financiero del usuario: balance disponible, ahorros, rendimientos, patrimonio total y totales por tipo en un rango de fechas opcional.",
  inputSchema: {
    start_date: z6.string().optional().describe("Fecha inicial YYYY-MM-DD para los totales del per\xEDodo."),
    end_date: z6.string().optional().describe("Fecha final YYYY-MM-DD para los totales del per\xEDodo.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    const unauth = requireAuth(ctx);
    if (unauth) return unauth;
    const { data, error } = await supabaseForUser(ctx).from("movements").select("date,type,amount,is_withdrawal,currency");
    if (error) return textResult(error.message, true);
    const rows = data ?? [];
    const sum = (fn) => rows.filter(fn).reduce((acc, r) => acc + Number(r.amount ?? 0), 0);
    const income = sum((r) => r.type === "income");
    const expense = sum((r) => r.type === "expense");
    const transfer = sum((r) => r.type === "transfer");
    const savingsIn = sum((r) => r.type === "savings" && !r.is_withdrawal);
    const savingsOut = sum((r) => r.type === "savings" && r.is_withdrawal);
    const yields = sum((r) => r.type === "yield");
    const balance = income + transfer - expense - savingsIn + savingsOut;
    const savings = savingsIn - savingsOut;
    const patrimonio = balance + savings + yields;
    const inRange = (r) => (!start_date || r.date >= start_date) && (!end_date || r.date <= end_date);
    const period = {
      income: sum((r) => r.type === "income" && inRange(r)),
      expense: sum((r) => r.type === "expense" && inRange(r)),
      savings: sum((r) => r.type === "savings" && !r.is_withdrawal && inRange(r)),
      transfer: sum((r) => r.type === "transfer" && inRange(r)),
      yield: sum((r) => r.type === "yield" && inRange(r))
    };
    const summary = { balance, savings, yields, patrimonio_total: patrimonio, period };
    return { ...textResult(summary), structuredContent: summary };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kpkkbsspwegnfcbddsvi";
var mcp_default = defineMcp({
  name: "cashflow-mcp",
  title: "CashFlow MCP",
  version: "0.1.0",
  instructions: "Herramientas de finanzas personales de CashFlow. Us\xE1 `financial_summary` para balance y patrimonio, `list_movements` y `create_movement` para movimientos, `list_categories` para obtener IDs de categor\xEDa, y `list_pending` / `create_pending_payment` para pagos e ingresos pendientes. Todas las operaciones son del usuario autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    financial_summary_default,
    list_movements_default,
    create_movement_default,
    list_categories_default,
    list_pending_default,
    create_pending_payment_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
